version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/www/public/wp-content/themes/nest-community
hooks:
  BeforeInstall:
    - location: deploy/before.sh
      runas: root
  AfterInstall:
    - location: deploy/after.sh
      runas: root
